version: "3"

services:
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        environment:
            STRAPI_HOST: ${STRAPI_HOST}
            STRPI_PORT: ${STRAPI_PORT}
            STRAPI_URL: ${STRAPI_URL}
            REGISTRY_URL: ${REGISTRY_URL}
            REGISTRY_PORT: ${REGISTRY_PORT}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_SSL: ${DATABASE_SSL}
            SEND_GRID_API_KEY: ${SEND_GRID_API_KEY}
            EMAIL_DEFAULT_FROM: ${EMAIL_DEFAULT_FROM}
            EMAIL_DEFAULT_REPLY_TO: ${EMAIL_DEFAULT_REPLY_TO}
            EMAIL_DEFAULT_TEST_ADDR: ${EMAIL_DEFAULT_TEST_ADDR}
            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
            STRAPI_LICENSE: ${STRAPI_LICENSE}
        ports:
            - "1337:1337"
        extra_hosts:
            - "host.docker.internal:172.17.0.1"CMD ["./start.sh"]
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        environment:
            NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
        ports:
            - "3000:3000"